<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Get-an-Interactive-TensorFlow-Session" data-toc-modified-id="Get-an-Interactive-TensorFlow-Session-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Get an Interactive TensorFlow Session</a></span></li><li><span><a href="#Hello-TensorFlow-!!!" data-toc-modified-id="Hello-TensorFlow-!!!-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Hello TensorFlow !!!</a></span></li><li><span><a href="#Constants" data-toc-modified-id="Constants-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Constants</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Placeholders" data-toc-modified-id="Placeholders-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Placeholders</a></span></li><li><span><a href="#Creating-Tensors-from-Existing-Objects" data-toc-modified-id="Creating-Tensors-from-Existing-Objects-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Creating Tensors from Existing Objects</a></span><ul class="toc-item"><li><span><a href="#0-Dimensional-Tensors-(Scalars)" data-toc-modified-id="0-Dimensional-Tensors-(Scalars)-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>0-Dimensional Tensors (Scalars)</a></span></li><li><span><a href="#1-Dimensional-Tensors-(Vectors)" data-toc-modified-id="1-Dimensional-Tensors-(Vectors)-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>1-Dimensional Tensors (Vectors)</a></span></li><li><span><a href="#2-Dimensional-Tensors-(Matrices)" data-toc-modified-id="2-Dimensional-Tensors-(Matrices)-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>2-Dimensional Tensors (Matrices)</a></span></li><li><span><a href="#3-Dimensional-Tensors" data-toc-modified-id="3-Dimensional-Tensors-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>3-Dimensional Tensors</a></span></li></ul></li><li><span><a href="#Variables" data-toc-modified-id="Variables-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="#Creating-Tensors-from-Library-Functions" data-toc-modified-id="Creating-Tensors-from-Library-Functions-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Creating Tensors from Library Functions</a></span></li><li><span><a href="#Close-the-interactive-session" data-toc-modified-id="Close-the-interactive-session-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Close the interactive session</a></span></li><li><span><a href="#Computation-Graphs" data-toc-modified-id="Computation-Graphs-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Computation Graphs</a></span><ul class="toc-item"><li><span><a href="#Building-and-Running-simple-computation-graph" data-toc-modified-id="Building-and-Running-simple-computation-graph-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Building and Running simple computation graph</a></span></li><li><span><a href="#Graph-on-Compute-Devices" data-toc-modified-id="Graph-on-Compute-Devices-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Graph on Compute Devices</a></span><ul class="toc-item"><li><span><a href="#List-the-devices-available" data-toc-modified-id="List-the-devices-available-10.2.1"><span class="toc-item-num">10.2.1&nbsp;&nbsp;</span>List the devices available</a></span></li><li><span><a href="#Default-placement" data-toc-modified-id="Default-placement-10.2.2"><span class="toc-item-num">10.2.2&nbsp;&nbsp;</span>Default placement</a></span></li><li><span><a href="#Placement-on-CPU" data-toc-modified-id="Placement-on-CPU-10.2.3"><span class="toc-item-num">10.2.3&nbsp;&nbsp;</span>Placement on CPU</a></span></li><li><span><a href="#Placement-on-CPU-and-GPU" data-toc-modified-id="Placement-on-CPU-and-GPU-10.2.4"><span class="toc-item-num">10.2.4&nbsp;&nbsp;</span>Placement on CPU and GPU</a></span></li></ul></li><li><span><a href="#Executing-Graph-g-as-Default" data-toc-modified-id="Executing-Graph-g-as-Default-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Executing Graph g as Default</a></span></li></ul></li><li><span><a href="#Logistic-Regression-with-TensorFlow" data-toc-modified-id="Logistic-Regression-with-TensorFlow-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Logistic Regression with TensorFlow</a></span></li><li><span><a href="#Logistic-Regression-with-Keras" data-toc-modified-id="Logistic-Regression-with-Keras-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Logistic Regression with Keras</a></span></li></ul></div>

# TensorFlow 101 <a class="tocSkip">

In [1]:
import tensorflow as tf
import numpy as np
print('TensorFlow Version :',tf.__version__)
import sys
print('Python interpreter and version:',sys.version)

TensorFlow Version : 1.9.0
Python interpreter and version: 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]


# Get an Interactive TensorFlow Session 

In [2]:
tfs = tf.InteractiveSession()

# Hello TensorFlow !!!

In [3]:
hello = tf.constant("Hello from TensorFlow Projects !!")
print(tfs.run(hello))

b'Hello from TensorFlow Projects !!'


# Constants

In [4]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  Tensor("x:0", shape=(), dtype=int32)
c2 (y):  Tensor("y:0", shape=(), dtype=float32)
c3 (z):  Tensor("z:0", shape=(), dtype=float32)


In [5]:
print('run([c1,c2,c3]) : ', tfs.run([c1, c2, c3]))

run([c1,c2,c3]) :  [5, 6.0, 7.0]


# Operations

In [6]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add:0", shape=(), dtype=float32)
op2 :  Tensor("Mul:0", shape=(), dtype=float32)


In [7]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  13.0
run(op2) :  42.0


# Placeholders

In [8]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [9]:
op4 = p1 * p2  # shorthand for tf.multiply(p1, p2)

In [10]:
print('run(op4,{p1:2.0, p2:3.0}) : ',tfs.run(op4,{p1:2.0, p2:3.0}))

run(op4,{p1:2.0, p2:3.0}) :  6.0


In [11]:
print('run(op4,feed_dict = {p1:3.0, p2:4.0}) : ',
      tfs.run(op4, feed_dict={p1: 3.0, p2: 4.0}))

run(op4,feed_dict = {p1:3.0, p2:4.0}) :  12.0


In [12]:
print('run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}):',
      tfs.run(op4, feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}))

run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}): [ 6. 12. 20.]


# Creating Tensors from Existing Objects

## 0-Dimensional Tensors (Scalars)

In [13]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_1:0", shape=(), dtype=float64)
run(tf_t) : 
 5.0


## 1-Dimensional Tensors (Vectors)

In [14]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print('a1dim Shape : ', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : \n', tfs.run(tf_t))

a1dim Shape :  (5,)
tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[0] :  Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


## 2-Dimensional Tensors (Matrices)

In [15]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print('a2dim Shape : ', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', tfs.run(tf_t))

a2dim Shape :  (3, 5)
tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


## 3-Dimensional Tensors

In [16]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('a3dim Shape : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t))

a3dim Shape :  (2, 2, 2)
tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Variables

In [17]:
# Linear model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

print("w:", w)
print("x:", x)
print("b:", b)
print("y:", y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_1:0", dtype=float32)


In [18]:
# initialize and print the variable y
tf.global_variables_initializer().run()
print('run(y,{x:[1,2,3,4]}) : ', tfs.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


# Creating Tensors from Library Functions

In [19]:
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


# Close the interactive session

In [20]:
tfs.close()

# Computation Graphs

## Building and Running simple computation graph

In [21]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.Session() as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})
print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


## Graph on Compute Devices

### List the devices available

In [22]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1652733233471954433
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14938472448
locality {
  bus_id: 1
  links {
  }
}
incarnation: 14642841451828407338
physical_device_desc: "device: 0, name: Quadro P5000, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


### Default placement

In [23]:
tf.reset_default_graph()

# Define model parameters
w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


### Placement on CPU

In [24]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


### Placement on CPU and GPU

In [25]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)
with tf.device('/device:GPU:0'):
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


## Executing Graph g as Default

In [26]:
g = tf.Graph()
output = 0

# Assume Linear Model y = w * x + b

with g.as_default():
    # Define model parameters
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Define model input and output
    x = tf.placeholder(tf.float32)
    y = w * x + b

with tf.Session(graph=g) as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})

print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


# Logistic Regression with TensorFlow

In [27]:
# load dslib
DSLIB_HOME = '../datasetslib'
import sys
if not DSLIB_HOME in sys.path:
    sys.path.append(DSLIB_HOME)
%reload_ext autoreload
%autoreload 2
import datasetslib as dslib

# set the datasets root folder before you do the datasetslib import
import os
dslib.dsroot = os.path.join(os.path.expanduser('~'),'datasets')

from datasetslib.utils import imutil
from datasetslib.utils import nputil
from datasetslib.mnist import MNIST

In [28]:
mnist=MNIST()

# prepare x and y data

x_train,y_train,x_test,y_test=mnist.load_data()

mnist.y_onehot = True
mnist.x_layout = imutil.LAYOUT_NP
x_test = mnist.load_images(x_test)
y_test = nputil.onehot(y_test)

print('Loaded x and y')
print('Train: x:{}, y:{}'.format(len(x_train),y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))

Already exists: /home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Already exists: /home/armando/datasets/mnist/train-labels-idx1-ubyte.gz
Already exists: /home/armando/datasets/mnist/t10k-images-idx3-ubyte.gz
Already exists: /home/armando/datasets/mnist/t10k-labels-idx1-ubyte.gz
Extracting and rearchiving as jpg files...
/home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/train-labels-idx1-ubyte.gz
Saving  train
Zip file not modified
/home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/t10k-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/t10k-labels-idx1-ubyte.gz
Saving  test
Zip file not modified
Loading in x and y... start
Loading in x and y... done
Loaded x and y
Train: x:60000, y:(60000,)
Test: x:(10000, 784), y:(10000, 10)


In [31]:
# define hyperparameters
learning_rate = 0.001
n_epochs = 5
mnist.batch_size = 100


# reset the graph if you run this cell again
tf.reset_default_graph()

# define input images
x = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_features])
# define output labels
y = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_classes])

# model paramteres
w = tf.Variable(tf.zeros([mnist.n_features, mnist.n_classes]))
b = tf.Variable(tf.zeros([mnist.n_classes]))

# the model itself
logits = tf.add(tf.matmul(x, w), b)
y_hat = tf.nn.softmax(logits)

# define loss function for training
epsilon = tf.keras.backend.epsilon()
y_hat_clipped = tf.clip_by_value(y_hat, epsilon, 1 - epsilon)
y_hat_log = tf.log(y_hat_clipped)
cross_entropy = -tf.reduce_sum(y * y_hat_log, axis=1)
loss_f = tf.reduce_mean(cross_entropy)

optimizer = tf.train.GradientDescentOptimizer
optimizer_f = optimizer(learning_rate=learning_rate).minimize(loss_f)

# define accuracy function for testing
predictions_check = tf.equal(tf.argmax(y_hat, 1), tf.argmax(y, 1))
accuracy_f = tf.reduce_mean(tf.cast(predictions_check, tf.float32))

# train and test
n_batches = int(60000/mnist.batch_size)

with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    for epoch in range(n_epochs):
        mnist.reset_index()
        for batch in range(n_batches):
            x_batch, y_batch = mnist.next_batch()
            feed_dict={x: x_batch, y: y_batch}
            batch_loss,_ = tfs.run([loss_f, optimizer_f],feed_dict=feed_dict )
            #print('Batch loss:{}'.format(batch_loss))
        
        feed_dict = {x: x_test, y: y_test}
        accuracy_score = tfs.run(accuracy_f, feed_dict=feed_dict)
        print('epoch {0:04d}  accuracy={1:.8f}'
              .format(epoch, accuracy_score))

epoch 0000  accuracy=0.73280001
epoch 0001  accuracy=0.72869998
epoch 0002  accuracy=0.74550003
epoch 0003  accuracy=0.75260001
epoch 0004  accuracy=0.74299997


# Logistic Regression with Keras

In [32]:
x_train_im = mnist.load_images(x_train)

x_train_im, x_test_im = x_train_im / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train_im, y_train, epochs=5)
model.evaluate(x_test_im, nputil.argmax(y_test))

Epoch 1/5
60000/60000 [==============================] - 3s 45us/step - loss: 0.7874 - acc: 0.8095
Epoch 2/5
60000/60000 [==============================] - 3s 42us/step - loss: 0.4585 - acc: 0.8792
Epoch 3/5
60000/60000 [==============================] - 2s 42us/step - loss: 0.4049 - acc: 0.8909
Epoch 4/5
60000/60000 [==============================] - 3s 42us/step - loss: 0.3780 - acc: 0.8965
Epoch 5/5
10000/10000 [==============================] - 0s 24us/step


[0.33530342621803283, 0.9097]